# Generated by Django 6.0.3 on 2026-03-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_number', models.IntegerField()),
                ('Inv_Total', models.IntegerField()),
                ('Inv_gst', models.IntegerField()),
                ('Inv_discount', models.IntegerField()),
                ('Inv_additional_charges', models.IntegerField()),
                ('Inv_internal_notes', models.IntegerField()),
                ('Inv_bill_date', models.DateField()),
                ('Inv_due_bill_date', models.DateField()),
                ('Inv_payment_mode', models.CharField()),
                ('Customer_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField()),
                ('Product_qty', models.IntegerField()),
                ('Inv_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField()),
                ('Product_price', models.IntegerField()),
                ('Product_stock', models.IntegerField()),
                ('Product_gst', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user'),
        ),
        migrations.CreateModel(
            name='Formet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_prefix', models.CharField(default='INV-')),
                ('Inv_footer', models.CharField(default='Thank you for your purchase! For queries, contact us at shop@billmate.in')),
                ('Inv_due_days', models.IntegerField(default=15)),
                ('Show_signature_area', models.BooleanField(default=True)),
                ('Show_TC', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=255)),
                ('Customer_mobile', models.IntegerField(max_length=10)),
                ('Customer_email', models.EmailField(max_length=254)),
                ('customer_bill_count', models.IntegerField(default=0)),
                ('customer_bill_spent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bizType', models.CharField()),
                ('Gstin', models.CharField()),
                ('City', models.CharField()),
                ('full_address', models.TextField()),
                ('Pan_number', models.CharField()),
                ('shop_logo', models.ImageField(upload_to='')),
                ('Gst_enable', models.BinaryField(default=True)),
                ('default_gst', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
    ]
