# Generated by Django 6.0.3 on 2026-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='business',
            name='bizName',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='Gstin',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='Pan_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='full_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='shop_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
