# Generated by Django 6.0.3 on 2026-03-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_remove_user_username_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sells',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='City',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='Gst_enable',
            field=models.CharField(default='True', max_length=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='Pan_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='bizName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='bizType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='default_gst',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
