# Generated by Django 6.0.3 on 2026-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_alter_business_gst_enable_alter_business_default_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='shop_logo',
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.IntegerField(default=9265186613),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_email',
            field=models.EmailField(default='customer@smartbill.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_mobile',
            field=models.IntegerField(default=9265186613),
        ),
    ]
