# Generated by Django 6.0.3 on 2026-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_remove_business_shop_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='Product_gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sells',
            name='Product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
